export { default as footerArt } from './footer-art.png';
export { default as header } from './header.png';
export { default as handGivingOutKey } from './hand-giving-key-real-estate-agent.png';
export { default as cheerfulFamily } from './young-cheerful-family-quarantine-insulation-spending-time-together-home.png';
export { default as manInSuit } from './man-in-suit.png';
export { default as property } from './property.png';
export { default as fatherHelpingChild } from './father-helping-daughter.png';
export { default as leadership } from './leadership.png';
export { default as contactImage } from './contact-image.png';
