export type IconNames =
  | 'AddIcon'
  | 'AppStore'
  | 'Avatar'
  | 'CloseIcon'
  | 'Facebook'
  | 'GooglePlay'
  | 'HamburgerMenu'
  | 'HelpIcon'
  | 'HorizontalLogoRed'
  | 'Instagram'
  | 'Linkedin'
  | 'LogoHorizontalBlack'
  | 'Logo'
  | 'Mail'
  | 'RightArrowWithout'
  | 'Telephone'
  | 'Twitter';
